### ISSUE TITLE
2pc

### ISSUE THREAD

**Issue by Spookyisnice** [kWAYTV/dma-cheat-base#3]
Are you retarded 2pc is ass and useless?

**Comment by kWAYTV** [comment]
> Are you retarded 2pc is ass and useless?

First of all, the whole purpose of DMA is using 2 pc's refrain from speaking without knowledge at least, and stop uploading detected pasted things that are only writing to memory using dma and even worse, 1 pc.

**Comment by kWAYTV** [comment]
> Are you retarded 2pc is ass and useless?

And i'll discuss this further with you, DMA's purpose of 2 pc's is to stay undetected through emulating a pcie device, if you do it any other way that involves using your gaming pc, like a kvm or something like that, it's obviously another detection vector, stop spreading false info.

Also in your own code, [only in this page](https://github.com/spookykokojunge/CS2-Dma-Radar/blob/main/Example/main.cpp):
- Full of `mem.Read's` alone, scatter reading is there for a reason.
- [In this line](https://github.com/spookykokojunge/CS2-Dma-Radar/blob/main/Example/main.cpp#L96) you are straight writing to memory, *it doesn't matter if it's through DMA*, that's gonna get detected at anytime, you are changing the game memory, a *simple memory integrity check* would defeat & detect your cheat.
- Am i watching a [full list of hardcoded offsets with no relation at all](https://github.com/spookykokojunge/CS2-Dma-Radar/blob/main/Example/main.cpp#L20)? 
- [Recompiling to turn features on or off ](https://github.com/spookykokojunge/CS2-Dma-Radar/blob/main/Example/main.cpp#L17)?

Please, i'm sorry if you felt attacked on the issue i did open in your repo, but it's because there's only few repos in github for cs2 dma's and you are gonna get a lot of *clueless people banned*. You don't need to come here and try to fuck up with a repo i made lol?
