### ISSUE TITLE
Pls include a stripped down version

### ISSUE THREAD

**Issue by Broimlookingforcode** [kWAYTV/dma-cheat-base#4]
Pls include a version without any kmbox files or references to kmbox

**Comment by kWAYTV** [comment]
> Pls include a version without any kmbox files or references to kmbox

Well basically i just have another complete new version using the complete dmalibrary and all of it's features, better  implementation and everything, just didn't upload yet because i'm using it for my personal projects, this was just a "boilerplate" so people can have an idea of how it works at a simple level

**Comment by kWAYTV** [comment]
Ok, i'll update the code as soon as i have time, today i have a busy day but i'll upload the new things i'm using

**Comment by TrueTuring** [comment]
would be also interested in a stripped down version of it without KMBox 

but also in the new version you didnt uploaded yet

any news about that?

**Comment by Broimlookingforcode** [comment]
i could help with that

**Comment by TrueTuring** [comment]
> i could help with that

Can you add me on discord? I am kinda new to DMA stuff 
Discord: .trickstrr

**Comment by kWAYTV** [comment]
I didn't include the stripped down version because i don't have time, but i included the new one so you guys can work with it.
